In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
matches = pd.read_csv('matches.csv')
deliveries = pd.read_csv('deliveries.csv')
matches.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [3]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [4]:
matches.shape,deliveries.shape

((756, 18), (179078, 21))

In [5]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [6]:
deliveries.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')

In [7]:
matches.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='str')

In [8]:
totalrun_df = deliveries.groupby(['match_id','inning']).sum()['total_runs'].reset_index()
totalrun_df

      match_id  inning  total_runs
0            1       1         207
1            1       2         172
2            2       1         184
3            2       2         187
4            3       1         183
...        ...     ...         ...
1523     11413       2         170
1524     11414       1         155
1525     11414       2         162
1526     11415       1         152
1527     11415       2         157

[1528 rows x 3 columns]

In [9]:
# grouping the 1st innings,2nd innings score in a particular matchid
# lets say match id = 1,so inning 1 score = 207,inning 2 score = 172,in that way

#totalrun_df = deliveries.groupby(['match_id','inning']).sum()['total_runs']

#totalrun_df

In [10]:
# capturing only the first innings,as we will be predicting for the second innnigs

totalrun_df = totalrun_df[totalrun_df['inning']==1]
totalrun_df

      match_id  inning  total_runs
0            1       1         207
2            2       1         184
4            3       1         183
6            4       1         163
8            5       1         157
...        ...     ...         ...
1518     11347       1         143
1520     11412       1         136
1522     11413       1         171
1524     11414       1         155
1526     11415       1         152

[756 rows x 3 columns]

In [11]:
totalrun_df['total_runs'] = totalrun_df['total_runs'].apply(lambda x:x+1)
totalrun_df

      match_id  inning  total_runs
0            1       1         208
2            2       1         185
4            3       1         184
6            4       1         164
8            5       1         158
...        ...     ...         ...
1518     11347       1         144
1520     11412       1         137
1522     11413       1         172
1524     11414       1         156
1526     11415       1         153

[756 rows x 3 columns]

In [12]:
matches.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='str')

In [13]:
'''
Merging the total first innings score df with the matches df,
where left side merging is done on "id" column of the matches
and right side merging is done on "match_id" column of the totalrun_df

'''

match_df = matches.merge(totalrun_df[['match_id','total_runs']],
                       left_on='id',right_on='match_id')

match_df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,208
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,185
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,184
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,164
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,144
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,137
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,172
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,156
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,153

In [14]:
match_df['team1'].unique()

<ArrowStringArray>
[        'Sunrisers Hyderabad',              'Mumbai Indians',
               'Gujarat Lions',      'Rising Pune Supergiant',
 'Royal Challengers Bangalore',       'Kolkata Knight Riders',
            'Delhi Daredevils',             'Kings XI Punjab',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors',     'Rising Pune Supergiants',
              'Delhi Capitals']
Length: 15, dtype: str

In [15]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals'
]

In [16]:
# replacing the Delhi Daredevils with Delhi Capitals

match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

# replacing the Deccan Chargers with Sunrises Hyderabad

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [17]:
match_df['team1'].isin(teams)

0       True
1       True
2      False
3      False
4       True
       ...
751     True
752     True
753     True
754     True
755     True
Name: team1, Length: 756, dtype: bool

In [18]:
match_df[match_df['team1'].isin(teams)]

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,208
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,185
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,158
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,7,179
7,8,IPL-2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,8,149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,144
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,137
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,172
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,156
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,153

In [19]:
# will consider only frequently occuring teams,
# which are mentioned in the teams list

match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

In [20]:
match_df['team1'].unique()

<ArrowStringArray>
[        'Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders',             'Kings XI Punjab',
              'Delhi Capitals',              'Mumbai Indians',
         'Chennai Super Kings',            'Rajasthan Royals']
Length: 8, dtype: str

In [21]:
match_df.shape

(641, 20)

In [22]:
match_df.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,208
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,158
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,7,179
7,8,IPL-2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,8,149
9,10,IPL-2017,Mumbai,12-04-2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,10,159

What dl_applied means

dl_applied is related to the Duckworth-Lewis method (D/L method) in cricket.

Values:

0 → No Duckworth-Lewis method was applied (normal match)

1 → Duckworth-Lewis method was applied (match was rain-affected or interrupted)

In limited-overs cricket, if rain interrupts a match, the team batting second may not get their full overs.

DL method adjusts the target score fairly based on:
Overs remaining
Wickets lost

Example:

Team 1 scores 180/5 in 20 overs.

Team 2 gets reduced overs due to rain.

DL method calculates a new target, so match is fair.

| match_id | team1   | team2   | dl_applied | ... |
| -------- | ------- | ------- | ---------- | --- |
| 1        | Mumbai  | Chennai | 0          | ... |
| 2        | Kolkata | Delhi   | 1          | ... |

dl_applied = 1 → use DL rules to check result.

dl_applied = 0 → normal 20-over match.

In [23]:
# checking the matches which resulted in dl method

match_df[match_df['dl_applied']==1].style.background_gradient(cmap = 'plasma')

In [24]:
# ignoring the rows which were DL method

match_df = match_df[match_df['dl_applied']==0]

# considering the match_id,city,winner and total runs

match_df = match_df[['match_id','city','winner','total_runs']]
match_df

     match_id           city                       winner  total_runs
0           1      Hyderabad          Sunrisers Hyderabad         208
4           5      Bangalore  Royal Challengers Bangalore         158
6           7         Mumbai               Mumbai Indians         179
7           8         Indore              Kings XI Punjab         149
9          10         Mumbai               Mumbai Indians         159
..        ...            ...                          ...         ...
751     11347         Mumbai               Mumbai Indians         144
752     11412        Chennai               Mumbai Indians         137
753     11413  Visakhapatnam               Delhi Capitals         172
754     11414  Visakhapatnam          Chennai Super Kings         156
755     11415      Hyderabad               Mumbai Indians         153

[626 rows x 4 columns]

In [25]:
deliveries.head(3)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [26]:
# merging matchdf with delevieries on match_id
delivery_df = match_df.merge(deliveries,on='match_id')
delivery_df.head(5)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
0,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [27]:
delivery_df.columns

Index(['match_id', 'city', 'winner', 'total_runs_x', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'is_super_over', 'wide_runs', 'bye_runs', 'legbye_runs', 'noball_runs',
       'penalty_runs', 'batsman_runs', 'extra_runs', 'total_runs_y',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='str')

In [28]:
# considering the 2nd innings 
delivery_df = delivery_df[delivery_df['inning'] == 2]
delivery_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,0,0,2,0,2,NaN,NaN,NaN
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [29]:
delivery_df.shape

(72413, 24)

If a value is not a number, don’t crash — just make it blank.


Suppose the column has:

["10", "5", "abc", "20"]


"10" → 10 ✅

"5" → 5 ✅

"abc" → ❌ not a number → blank (NaN)

"20" → 20 ✅

Other possible options (for understanding)

errors='raise' → ❌ stop the program and show an error (default)

errors='coerce' → 🧹 quietly replace wrong values with blank (NaN)

errors='ignore' → do nothing, keep values as they are



 errors decides how to handle bad or non-numeric data.

In [30]:
delivery_df['total_runs_y'] = pd.to_numeric(delivery_df['total_runs_y'],errors='coerce')

In [31]:
delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs_y'].cumsum()

In [32]:
delivery_df['current_score']

125         1
126         1
127         1
128         3
129         7
         ...
149573    152
149574    154
149575    155
149576    157
149577    157
Name: current_score, Length: 72413, dtype: int64

In [33]:
delivery_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,1,0,1,NaN,NaN,NaN,1
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,1
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,1
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,0,2,0,2,NaN,NaN,NaN,3
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,0,4,0,4,NaN,NaN,NaN,7

# current score of particular match

'''
So by observation we can observe that in the matchdf we had taken
firstinnings total runs,right and in the second case,that is in the 
delivery dataframe we considered second inning runs,as our main aim
is to find the probability of either teams to win or loose,we need 
current runs and runrate,so for current runs,we can apply groupby
on matchid and take the cummulative sum wrt total_runs_y,now,basically
totalruns was present in matchdf as well as deliveries_df,but as we merged
both the dataframes,it resulted in total_runs_x,and total_runs_y,
so total_runs_x is the first innings runs and total_runs_y are the second
innings runs,ball by ball,by applying cummulative sum,this becomes 
current score


total_runs_y gives the run scored after each ball,so in the second innings,
we want to get the total second innings runs,so we will groupby match id
and will apply the cummulative sum


'''



delivery_df['current_score'] = delivery_df.groupby('match_id').cumsum()['total_runs_y']

delivery_df.head()

In [34]:
# runs left 

delivery_df['runs_left'] = delivery_df['total_runs_x']-delivery_df['current_score']

delivery_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,1,0,1,NaN,NaN,NaN,1,207
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,NaN,NaN,NaN,1,207
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,NaN,NaN,NaN,1,207
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,2,0,2,NaN,NaN,NaN,3,205
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,4,0,4,NaN,NaN,NaN,7,201

In [35]:
'''
if one ball is played,then balls left = 120-1 = 119........(1)
if two balls are played,then balls left = 120-2 = 118

so similarly if over=1,over has 6 balls right,so 1*6 = 6
now,ball = 1,so 6+1 = 7,now 126-7 = 119,which is same as (1)

so we'll use balls_left = 126-(over*6+current_ball)

'''

# balls left


delivery_df['balls_left'] = 126-(delivery_df['over']*6+delivery_df['ball'])

delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,1,0,1,NaN,NaN,NaN,1,207,119
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,207,118
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,207,117
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,2,0,2,NaN,NaN,NaN,3,205,116
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,4,0,4,NaN,NaN,NaN,7,201,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149573,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,1,0,1,NaN,NaN,NaN,152,1,4
149574,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,2,0,2,NaN,NaN,NaN,154,-1,3
149575,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,1,0,1,SR Watson,run out,KH Pandya,155,-2,2
149576,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,2,0,2,NaN,NaN,NaN,157,-4,1
149577,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,SN Thakur,lbw,NaN,157,-4,0

In [36]:
list(delivery_df['player_dismissed'].unique())

[nan,
 'Mandeep Singh',
 'CH Gayle',
 'KM Jadhav',
 'TM Head',
 'Sachin Baby',
 'STR Binny',
 'SR Watson',
 'S Aravind',
 'TS Mills',
 'YS Chahal',
 'AP Tare',
 'KK Nair',
 'SW Billings',
 'SV Samson',
 'CH Morris',
 'CR Brathwaite',
 'PJ Cummins',
 'RR Pant',
 'S Nadeem',
 'PA Patel',
 'JC Buttler',
 'RG Sharma',
 'KH Pandya',
 'KA Pollard',
 'N Rana',
 'M Vohra',
 'AR Patel',
 'SP Narine',
 'RV Uthappa',
 'MJ McClenaghan',
 'S Dhawan',
 'DA Warner',
 'MC Henriques',
 'DJ Hooda',
 'Yuvraj Singh',
 'BCJ Cutting',
 'WP Saha',
 'HM Amla',
 'EJG Morgan',
 'GJ Maxwell',
 'DA Miller',
 'MM Sharma',
 'KC Cariappa',
 'C de Grandhomme',
 'G Gambhir',
 'YK Pathan',
 'SA Yadav',
 'CR Woakes',
 'I Sharma',
 'AD Mathews',
 'SS Iyer',
 'CJ Anderson',
 'K Rabada',
 'V Kohli',
 'AB de Villiers',
 'P Negi',
 'S Badree',
 'MK Pandey',
 'MJ Guptill',
 'SE Marsh',
 'Anureet Singh',
 'SP Jackson',
 'KV Sharma',
 'A Choudhary',
 'MN Samuels',
 'Mohammed Shami',
 'Z Khan',
 'CA Lynn',
 'LMP Simmons',
 'HH Pandya',
 'Kuldeep Yadav',
 'A Mishra',
 'AT Rayudu',
 'R Dravid',
 'JH Kallis',
 'W Jaffer',
 'MV Boucher',
 'B Akhil',
 'CL White',
 'AA Noffke',
 'SB Joshi',
 'K Goel',
 'JR Hopes',
 'KC Sangakkara',
 'V Sehwag',
 'S Chanderpaul',
 'LRPL Taylor',
 'BB McCullum',
 'RT Ponting',
 'SC Ganguly',
 'Mohammad Hafeez',
 'M Kaif',
 'Kamran Akmal',
 'DS Lehmann',
 'L Ronchi',
 'ST Jayasuriya',
 'SM Pollock',
 'DJ Bravo',
 'MA Khote',
 'Harbhajan Singh',
 'GC Smith',
 'RA Jadeja',
 'D Salunkhe',
 'SS Tiwary',
 'AM Nayar',
 'M Rawat',
 'DPMD Jayawardene',
 'SM Katich',
 'TM Srivastava',
 'IK Pathan',
 'B Chipli',
 'P Kumar',
 'DW Steyn',
 'AM Rahane',
 'RR Sarwan',
 'Salman Butt',
 'AB Agarkar',
 'BJ Hodge',
 'LR Shukla',
 'DJ Hussey',
 'DB Das',
 'Umar Gul',
 'AB Dinda',
 'Misbah-ul-Haq',
 'Shoaib Malik',
 'KD Karthik',
 'PJ Sangwan',
 'R Bhatia',
 'Mohammad Asif',
 'GD McGrath',
 'SA Asnodkar',
 'HH Gibbs',
 'AC Gilchrist',
 'YV Takawale',
 'S Vidyut',
 'SP Fleming',
 'SK Raina',
 'JA Morkel',
 'MS Dhoni',
 'CK Kapugedera',
 'J Arunkumar',
 'PP Chawla',
 'VRV Singh',
 'DB Ravi Teja',
 'SB Styris',
 'SB Bangar',
 'WPUJC Vaas',
 'AD Mascarenhas',
 'SK Warne',
 'MK Tiwary',
 'TM Dilshan',
 'MF Maharoof',
 'VY Mahesh',
 'SR Tendulkar',
 'Younis Khan',
 'Niraj Patel',
 'Shahid Afridi',
 'Y Venugopal Rao',
 'PP Ojha',
 'RP Singh',
 'DT Patil',
 'A Kumble',
 'LPC Silva',
 'H Das',
 'Sohail Tanvir',
 'DR Smith',
 'PR Shah',
 'SD Chitnis',
 'A Nehra',
 'VS Yeligati',
 'S Badrinath',
 'MS Gony',
 'L Balaji',
 'LA Pomersbach',
 'A Mukund',
 'VVS Laxman',
 'A Chopra',
 'A Flintoff',
 'ML Hayden',
 'JDP Oram',
 'T Henderson',
 'MM Patel',
 'Kamran Khan',
 'KP Pietersen',
 'R Bishnoi',
 'R Vinay Kumar',
 'JD Ryder',
 'Joginder Sharma',
 'Yashpal Singh',
 'RS Bopara',
 'JP Duminy',
 'RJ Quiney',
 'AS Raut',
 'AN Ghosh',
 'BAW Mendis',
 'PC Valthaty',
 'SP Goswami',
 'RE van der Merwe',
 'SK Trivedi',
 'MN van Wyk',
 'NV Ojha',
 'LA Carseldine',
 'M Manhas',
 'S Sohal',
 'RJ Harris',
 'TL Suman',
 'WA Mota',
 'M Vijay',
 'M Morkel',
 'A Symonds',
 'Shoaib Ahmed',
 'DS Kulkarni',
 'C Nanda',
 'SL Malinga',
 'J Botha',
 'A Singh',
 'SS Shaikh',
 'B Lee',
 'AA Bilakhia',
 'Anirudh Singh',
 'AA Jhunjhunwala',
 'P Dogra',
 'A Uniyal',
 'JM Kemp',
 'R Ashwin',
 'M Muralitharan',
 'OA Shah',
 'RS Gavaskar',
 'SE Bond',
 'M Kartik',
 'DP Nannes',
 'MS Bisla',
 'AB Barath',
 'CA Pujara',
 'Y Nagar',
 'S Ladda',
 'GJ Bailey',
 'J Theron',
 'SJ Srivastava',
 'R Sathish',
 'MJ Lumb',
 'MD Mishra',
 'Jaskaran Singh',
 'KAJ Roach',
 'CK Langeveldt',
 'FY Fazal',
 'AC Voges',
 'S Narwal',
 'SW Tait',
 'R Sharma',
 'A Mithun',
 'Harmeet Singh',
 'R McLaren',
 'PD Collingwood',
 'S Sriram',
 'AP Dole',
 'KP Appanna',
 'MR Marsh',
 'Pankaj Singh',
 'B Sumanth',
 'AG Paunikar',
 'DJ Jacobs',
 'IR Jaggi',
 'DT Christian',
 'AL Menaria',
 'Sunny Singh',
 'MA Agarwal',
 'JJ van der Wath',
 'R Ninan',
 'AUK Pathan',
 'AJ Finch',
 'MEK Hussey',
 'S Anirudha',
 'S Randiv',
 'TR Birt',
 'Bipul Sharma',
 'CA Ingram',
 'DH Yagnik',
 'AC Blizzard',
 'AB McDonald',
 'KB Arun Karthik',
 'BA Bhatt',
 'JEC Franklin',
 'DL Vettori',
 'RE Levi',
 'DJ Harris',
 'Ankit Sharma',
 'HV Patel',
 'KK Cooper',
 'AA Chavan',
 'GB Hogg',
 'F du Plessis',
 'Shakib Al Hasan',
 'RN ten Doeschate',
 'N Saini',
 'Azhar Mahmood',
 'RJ Peterson',
 'A Ashish Reddy',
 'Gurkeerat Singh',
 'PA Reddy',
 'UBT Chand',
 'AD Russell',
 'UT Yadav',
 'Sunny Gupta',
 'VR Aaron',
 'MC Juneja',
 'B Laughlin',
 'NLTC Perera',
 'BMAJ Mendis',
 'GH Vihari',
 'SMSM Senanayake',
 'KL Rahul',
 'J Syed Mohammad',
 'R Dhawan',
 'MG Johnson',
 'Q de Kock',
 'BB Samantray',
 'BJ Rohrer',
 'DJG Sammy',
 'P Awana',
 'JP Faulkner',
 'NM Coulter-Nile',
 'CM Gautam',
 'NJ Maddinson',
 'JDS Neesham',
 'B Kumar',
 'SPD Smith',
 'TG Southee',
 'PV Tambe',
 'BR Dunk',
 'RR Rossouw',
 'MA Starc',
 'KW Richardson',
 'S Rana',
 'Imran Tahir',
 'R Shukla',
 'R Tewatia',
 'SA Abbott',
 'KS Williamson',
 'Iqbal Abdulla',
 'SN Khan',
 'D Wiese',
 'Karanveer Singh',
 'Sandeep Sharma',
 'J Suchith',
 'NS Naik',
 'JO Holder',
 'Parvez Rasool',
 'MP Stoinis',
 'Swapnil Singh',
 'JJ Bumrah',
 'C Munro',
 'CJ Jordan',
 'DL Chahar',
 'M Wood',
 'R Singh',
 'Rashid Khan',
 'S Kaul',
 'Washington Sundar',
 'V Shankar',
 'TA Boult',
 'H Klaasen',
 'RA Tripathi',
 'BA Stokes',
 'K Gowtham',
 'JD Unadkat',
 'R Bhui',
 'J Archer',
 'P Shaw',
 'L Plunkett',
 'E Lewis',
 'Ishan Kishan',
 'AS Yadav',
 'M Markande',
 'Mustafizur Rahman',
 'AJ Tye',
 'BB Sran',
 'AS Rajpoot',
 'S Gill',
 'S Mavi',
 'M Lomror',
 'D Shorey',
 'A Hales',
 'M Ali',
 'AD Nath',
 'T Curran',
 'P Chopra',
 'D Short',
 'Mohammed Siraj',
 'S Hetmyer',
 'J Bairstow',
 'H Vihari',
 'C Ingram',
 'S Dube',
 'P R Barman',
 'S Gopal',
 'S Lamichhane',
 'Mohammad Nabi',
 'SD Lad',
 'L Livingstone',
 'K Ahmed',
 'A Turner',
 'K Paul',
 'R Parag',
 'SN Thakur',
 'S Rutherford',
 'N Pooran',
 'H Viljoen',
 'M Santner',
 'S Singh',
 'M Ur Rahman']

In [37]:
list(delivery_df['player_dismissed'].unique())[:2]

[nan, 'Mandeep Singh']

In [38]:

# filling nan values with "0"

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")

# now we will convert this player_dismissed col into a boolean col
# if the player is not dismissed then it's 0 else its 1

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x:x if x=="0" else "1")

# converting string to int

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')


delivery_df['player_dismissed'].unique()

array([0, 1])

🔸 Use astype(int) when converting True/False → 1/0

🔸 Use astype('int') only when column is already numeric

.astype(int)      # Python built-in integer type

.astype('int')    # Pandas dtype name written as string

In [39]:
### A wicket falls when player_dismissed is NOT null
# So we convert it into a binary indicator:
# Wicket = 1 if player dismissed
# No wicket = 0
#Create wicket indicator column
delivery_df['is_wicket'] = delivery_df['player_dismissed'].notna().astype(int)

In [40]:
delivery_df['is_wicket']

125       1
126       1
127       1
128       1
129       1
         ..
149573    1
149574    1
149575    1
149576    1
149577    1
Name: is_wicket, Length: 72413, dtype: int64

In [41]:
print(len(delivery_df['is_wicket']))

72413

### delivery_df['is_wicket'] = delivery_df['player_dismissed'].notna().astype(int)

🔹Step 1: delivery_df['player_dismissed']

This column contains:

Player name → when a wicket falls

NaN (empty) → when no wicket falls on that ball

Example:

player_dismissed

NaN
NaN
"RG Sharma"
NaN
"V Kohli"

🔹 Step 2: .notna()
delivery_df['player_dismissed'].notna()


This checks “is there a value or not?”

If player name present → True

If NaN → False

Result:

False
False
True
False
True


👉 Meaning:

True = wicket fell

False = no wicket

🔹 Step 3: .astype(int)
.notna().astype(int)


This converts:

True → 1

False → 0

Result:

0
0
1
0
1

In [42]:
#Cumulative wickets per match
delivery_df['wickets_fallen'] = (
    delivery_df.groupby('match_id')['is_wicket'].cumsum()
)

In [43]:
delivery_df.tail(5)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,is_wicket,wickets_fallen
149573,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,1,0,NaN,NaN,152,1,4,1,120
149574,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,2,0,NaN,NaN,154,-1,3,1,121
149575,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,1,1,run out,KH Pandya,155,-2,2,1,122
149576,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,2,0,NaN,NaN,157,-4,1,1,123
149577,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,1,lbw,NaN,157,-4,0,1,124

delivery_df.groupby('match_id')  Group all rows by match number

['is_wicket']   From each match, look only at the is_wicket column

groupby → separates matches

cumsum → keeps adding

assignment → saves result

In [44]:
delivery_df['wickets_fallen']

125         1
126         2
127         3
128         4
129         5
         ...
149573    120
149574    121
149575    122
149576    123
149577    124
Name: wickets_fallen, Length: 72413, dtype: int64

In [45]:
#Remaining wickets
delivery_df['wickets_remaining'] = 10 - delivery_df['wickets_fallen']

In [46]:
delivery_df['wickets_remaining']

125         9
126         8
127         7
128         6
129         5
         ...
149573   -110
149574   -111
149575   -112
149576   -113
149577   -114
Name: wickets_remaining, Length: 72413, dtype: int64

In [47]:
delivery_df[['match_id', 'player_dismissed', 'wickets_fallen', 'wickets_remaining']].head(2)

     match_id  player_dismissed  wickets_fallen  wickets_remaining
125         1                 0               1                  9
126         1                 0               2                  8

In [48]:
delivery_df['wickets_remaining'] = 10 - (
    delivery_df.groupby('match_id')['player_dismissed']
    .transform(lambda x: x.notna().cumsum())
)

In [49]:
delivery_df['wickets_remaining']

125         9
126         8
127         7
128         6
129         5
         ...
149573   -110
149574   -111
149575   -112
149576   -113
149577   -114
Name: wickets_remaining, Length: 72413, dtype: int64

# wickets fallen 

wickets = delivery_df.groupby('match_id').cumsum()['player_dismissed'].values

delivery_df['wickets'] = 10-wickets

delivery_df

In [50]:
# current run rate
delivery_df['cur_run_rate'] = (delivery_df['current_score']*6)/(120-delivery_df['balls_left'])

In [51]:


# required run rate
delivery_df['req_run_rate'] = (delivery_df['runs_left']*6)/(delivery_df['balls_left'])

delivery_df.head(3)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,dismissal_kind,fielder,current_score,runs_left,balls_left,is_wicket,wickets_fallen,wickets_remaining,cur_run_rate,req_run_rate
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,NaN,NaN,1,207,119,1,1,9,6.0,10.436975
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,NaN,NaN,1,207,118,1,2,8,3.0,10.525424
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,NaN,NaN,1,207,117,1,3,7,2.0,10.615385

In [52]:
def resultfun(row):
    
    return 1 if row['batting_team'] == row['winner'] else 0

In [53]:
delivery_df['result'] = delivery_df.apply(resultfun,axis=1)
delivery_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,fielder,current_score,runs_left,balls_left,is_wicket,wickets_fallen,wickets_remaining,cur_run_rate,req_run_rate,result
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,NaN,1,207,119,1,1,9,6.0,10.436975,0
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,NaN,1,207,118,1,2,8,3.0,10.525424,0
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,NaN,1,207,117,1,3,7,2.0,10.615385,0
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,NaN,3,205,116,1,4,6,4.5,10.603448,0
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,NaN,7,201,115,1,5,5,8.4,10.486957,0

In [54]:
#sn.countplot(delivery_df['result'])

In [55]:
delivery_df['wickets'] = delivery_df['wickets_remaining']

In [56]:
final_df = delivery_df[['batting_team','bowling_team','city','runs_left',
                        'balls_left','wickets','total_runs_x','cur_run_rate',
                        'req_run_rate','result']]

final_df.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,cur_run_rate,req_run_rate,result
125,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,119,9,208,6.0,10.436975,0
126,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,118,8,208,3.0,10.525424,0
127,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,117,7,208,2.0,10.615385,0
128,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,205,116,6,208,4.5,10.603448,0
129,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,201,115,5,208,8.4,10.486957,0

In [57]:
final_df.shape

(72413, 10)

In [58]:
final_df.isnull().sum()

batting_team      0
bowling_team      0
city            832
runs_left         0
balls_left        0
wickets           0
total_runs_x      0
cur_run_rate      0
req_run_rate      5
result            0
dtype: int64

In [59]:
# dropping of null values


final_df = final_df.dropna()

final_df.isnull().sum()

batting_team    0
bowling_team    0
city            0
runs_left       0
balls_left      0
wickets         0
total_runs_x    0
cur_run_rate    0
req_run_rate    0
result          0
dtype: int64

In [60]:
final_df = final_df[final_df['balls_left'] != 0]

In [61]:
data = final_df.copy()

test = data['result']

train = data.drop(['result'],axis = 1)

train.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,cur_run_rate,req_run_rate
125,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,119,9,208,6.0,10.436975
126,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,118,8,208,3.0,10.525424
127,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,117,7,208,2.0,10.615385
128,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,205,116,6,208,4.5,10.603448
129,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,201,115,5,208,8.4,10.486957

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(train,test,test_size=0.2,random_state=1)

X_train.shape,X_test.shape

((57073, 9), (14269, 9))

In [63]:
X_train.columns

Index(['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left',
       'wickets', 'total_runs_x', 'cur_run_rate', 'req_run_rate'],
      dtype='str')

In [64]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn import metrics

In [65]:
# batting team,bowling team and city are categorical columns
# they will be converted to numeric using onehot encoder
cf = ColumnTransformer(
    [('encoder',
      OneHotEncoder(drop='first', sparse_output=False),
      ['batting_team', 'bowling_team', 'city'])],
    remainder='passthrough'
)


cf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])
],remainder='passthrough')

In [66]:
# creating the pipeline


pipe = Pipeline(steps=[
    ('step1',cf),
    ('step2',LogisticRegression(solver='liblinear'))
])

# fitting the training data

pipe.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [67]:
y_pred = pipe.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.7940290139463172

In [68]:
pipe.predict_proba(X_test)[10]

array([0.39804903, 0.60195097])

In [69]:
# Selecting Random Forest Classifier

pipe2 = Pipeline(steps=[
    ('step1',cf),
    ('step2',RandomForestClassifier())
])

pipe2.fit(X_train,y_train)
print(metrics.accuracy_score(y_test,pipe2.predict(X_test)))

0.9980377041138132

In [70]:
# oth index is loose prob and 1st index is win prob

pipe2.predict_proba(X_test)[10]

array([0.06, 0.94])

In [71]:
'''
I will go with Logistic Regression because i need to 
showcase the probability right,even though Random Forest is 
giving much accurate result,but RandomForest is being baised
at one side,as you can observe the prob of winning for 10th sample
is shown as 98% and 2% loose prob,this is kind of tooo strong or may
be sometimes unrealistic,so its better to use a model which gives equal 
justice towards both side,as we also don't know which team will outperform 
and win the game!

'''

"\nI will go with Logistic Regression because i need to \nshowcase the probability right,even though Random Forest is \ngiving much accurate result,but RandomForest is being baised\nat one side,as you can observe the prob of winning for 10th sample\nis shown as 98% and 2% loose prob,this is kind of tooo strong or may\nbe sometimes unrealistic,so its better to use a model which gives equal \njustice towards both side,as we also don't know which team will outperform \nand win the game!\n\n"

In [72]:
# saving the logistic regression model

import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))